#!/usr/bin/env bash
# Deploy Codesteward cloud trial to a single DigitalOcean Droplet.
# Requires: doctl authenticated (doctl auth init) with Droplet create scope.
#
# This is NOT the generic Docker Marketplace app — user-data runs our cloud-init
# which clones the repo and executes deploy/cloud/first-boot.sh (Keycloak + stack).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLOUD_INIT="${CLOUD_INIT_FILE:-$SCRIPT_DIR/cloud-init.yaml}"

DROPLET_NAME="${DROPLET_NAME:-codesteward}"
REGION="${REGION:-nyc3}"
SIZE="${SIZE:-s-2vcpu-4gb}"
IMAGE="${IMAGE:-ubuntu-24-04-x64}"
DOMAIN="${DOMAIN:-}"
ACME_EMAIL="${ACME_EMAIL:-}"
IMAGE_TAG="${IMAGE_TAG:-1.4.0}"
GIT_REF="${GIT_REF:-main}"

command -v doctl >/dev/null 2>&1 || {
  echo "doctl is required. Install: https://docs.digitalocean.com/reference/doctl/how-to/install/"
  echo "Then: doctl auth init"
  exit 1
}

[[ -f "$CLOUD_INIT" ]] || {
  echo "cloud-init not found: $CLOUD_INIT"
  exit 1
}

# Optional: write boot.env fragment into a rendered user-data so IMAGE_TAG/DOMAIN apply
USER_DATA="$(mktemp)"
trap 'rm -f "$USER_DATA"' EXIT

# Prepend env exports via a shellscript part — DO runs cloud-config; we inject write_files
{
  echo "#cloud-config"
  echo "# Generated by deploy/cloud/do/deploy.sh — Codesteward trial"
  echo "package_update: true"
  echo "packages:"
  echo "  - curl"
  echo "  - ca-certificates"
  echo "  - gnupg"
  echo "  - git"
  echo "  - openssl"
  echo "  - python3"
  echo "  - jq"
  echo "write_files:"
  echo "  - path: /etc/codesteward/boot.env"
  echo "    permissions: '0600'"
  echo "    content: |"
  echo "      DOMAIN=${DOMAIN}"
  echo "      ACME_EMAIL=${ACME_EMAIL}"
  echo "      IMAGE_TAG=${IMAGE_TAG}"
  echo "      GIT_REF=${GIT_REF}"
  echo "runcmd:"
  echo "  - |"
  echo "    set -euo pipefail"
  echo "    exec >>/var/log/codesteward-user-data.log 2>&1"
  echo "    echo \"codesteward DO user-data start \$(date -u)\""
  echo "    if [[ -f /etc/codesteward/boot.env ]]; then set -a; . /etc/codesteward/boot.env; set +a; fi"
  echo "    INSTALL_DIR=/opt/codesteward"
  echo "    REF=\"\${GIT_REF:-main}\""
  echo "    if [[ ! -d \"\$INSTALL_DIR/deploy/cloud\" ]]; then"
  echo "      git clone --depth 1 --branch \"\$REF\" https://github.com/Codesteward/codesteward.git \"\$INSTALL_DIR\" \\"
  echo "        || git clone --depth 1 https://github.com/Codesteward/codesteward.git \"\$INSTALL_DIR\""
  echo "    fi"
  echo "    export DOMAIN ACME_EMAIL IMAGE_TAG"
  echo "    bash \"\$INSTALL_DIR/deploy/cloud/first-boot.sh\""
} >"$USER_DATA"

# Attach account SSH keys when present (avoid password-only droplets)
SSH_FLAGS=()
if [[ -n "${SSH_KEYS:-}" ]]; then
  SSH_FLAGS=(--ssh-keys "$SSH_KEYS")
else
  KEY_IDS="$(doctl compute ssh-key list --format ID --no-header 2>/dev/null | tr '\n' ',' | sed 's/,$//')"
  if [[ -n "$KEY_IDS" ]]; then
    SSH_FLAGS=(--ssh-keys "$KEY_IDS")
  else
    echo "Warning: no SSH keys in this DO account. Add one in the control panel or set SSH_KEYS=id1,id2"
  fi
fi

echo "Creating Droplet name=$DROPLET_NAME region=$REGION size=$SIZE image=$IMAGE"
echo "  IMAGE_TAG=$IMAGE_TAG DOMAIN=${DOMAIN:-<public-ip>} GIT_REF=$GIT_REF"

if doctl compute droplet get "$DROPLET_NAME" >/dev/null 2>&1; then
  echo "Droplet already exists: $DROPLET_NAME"
  exit 1
fi

doctl compute droplet create "$DROPLET_NAME" \
  --image "$IMAGE" \
  --size "$SIZE" \
  --region "$REGION" \
  --user-data-file "$USER_DATA" \
  --wait \
  --tag-names codesteward,cloud-trial \
  "${SSH_FLAGS[@]}"

IP="$(doctl compute droplet get "$DROPLET_NAME" --format PublicIPv4 --no-header)"

echo ""
echo "Created $DROPLET_NAME at $IP"
echo "First-boot takes ~5–15 minutes (Docker + GHCR pulls + Keycloak)."
echo "  doctl compute ssh $DROPLET_NAME --ssh-command 'sudo cat /var/lib/codesteward/credentials.txt'"
echo "  Log: doctl compute ssh $DROPLET_NAME --ssh-command 'sudo tail -f /var/log/codesteward-user-data.log'"
echo "UI (after boot): https://$IP/  (accept self-signed cert)"
[[ -n "$DOMAIN" ]] && echo "Point $DOMAIN A/AAAA to $IP if using a custom domain"
